---
title: "Drivers of Microbial a-Diversity in Indiana CFI plots"
author: "Ashley"
date: "3/2/2022"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(lme4)
library(vegan)
library(ggeffects)
library(cowplot)
library(ggpubr)
library(sjPlot)
library(sensemakr)


#New soil pH and Fe data:
ehp_soildat_all=read.csv("fe_pH_Compiled.csv") %>% 
    mutate(plotID=as.numeric(substr(Plot, 2, 5))) %>% 
 arrange(plotID) %>% 
  select(-County, -Unit, -Plot, -c_percent, -n_percent, -cn) 

#reading in and cleaning bacteria sequence file: 0-5cm
shal_bacteria_data_1=read.csv("newdata/Bacteria/IndianaCFI16S_Prop_seqtab_0_5_2021_04_16.csv",head =TRUE, row.names=1)
shal_bacteria_data_1<-t(shal_bacteria_data_1) 

shal_bacteria_data=as.data.frame(shal_bacteria_data_1) %>% 
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "amplicon")) %>% 
  mutate(plot=substr(plot, 2, 5)) %>% #36 plots
  select(-amplicon, -upperDepth, -lowerDepth) %>% 
  arrange(plot)
shal_bacteria_plots=shal_bacteria_data$plot
shal_bacteria_data=shal_bacteria_data %>% column_to_rownames(var="plot")

#reading in and cleaning bacteria sequence file: 5-10cm
deep_bacteria_data_1=read.csv("newdata/Bacteria/IndianaCFI16S_Prop_seqtab_5_10_2022_02_16.csv",head =TRUE, row.names=1)
deep_bacteria_data_1<-t(deep_bacteria_data_1) 

deep_bacteria_data=as.data.frame(deep_bacteria_data_1) %>% 
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "amplicon")) %>% 
  mutate(plot=substr(plot, 2, 5)) %>% #36 plots
  select(-amplicon,-upperDepth, -lowerDepth) %>% 
  arrange(plot)
deep_bacteria_plots=deep_bacteria_data$plot
deep_bacteria_data=deep_bacteria_data %>% column_to_rownames(var="plot") 

#reading in and cleaning AM sequence file: 0-5
shal_amfungi_data_1=read.csv("newdata/AMF/IndianaCFIAMF_seqtab_prop_0_5_2022_02_24.csv",head =TRUE, row.names=1) 
shal_amfungi_data_1<-t(shal_amfungi_data_1)

shal_amfungi_data=as.data.frame(shal_amfungi_data_1) %>%  
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "microbialGroup")) %>% 
    mutate(plot=as.numeric(substr(plot, 2, 5))) %>% 
  select(-upperDepth, -lowerDepth, -microbialGroup)  %>% 
  arrange(plot)
shal_amfungi_plots=shal_amfungi_data$plot
shal_amfungi_data=shal_amfungi_data %>% column_to_rownames(var="plot")

#reading in and cleaning AM sequence file: 5-10
deep_amfungi_data_1=read.csv("newdata/AMF/IndianaCFIAMF_seqtab_prop_5_10_2022_02_24.csv",head =TRUE, row.names=1) 
deep_amfungi_data_1<-t(deep_amfungi_data_1)

deep_amfungi_data=as.data.frame(deep_amfungi_data_1) %>%  
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "microbialGroup")) %>% 
    mutate(plot=as.numeric(substr(plot, 2, 5))) %>% 
  select(-upperDepth, -lowerDepth,-microbialGroup)  %>% 
  arrange(plot)
deep_amfungi_plots=deep_amfungi_data$plot
deep_amfungi_data=deep_amfungi_data %>% column_to_rownames(var="plot")


#reading in and cleaning Fungi sequence file: 0-5cm
shal_fungi_data_1=read.csv("newdata/Fungi/IndianaCFIITSProp_seqtab_0_5_2022_02_24_1.csv",head =TRUE, row.names=1)
shal_fungi_data_1<-t(shal_fungi_data_1)

shal_fungi_data=as.data.frame(shal_fungi_data_1) %>% 
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "amplicon")) %>% 
  mutate(plot=as.numeric(substr(plot, 2, 5))) %>% 
  select(-upperDepth, -lowerDepth, -amplicon) %>% 
  arrange(plot)
shal_fungi_plots=shal_fungi_data$plot
shal_fungi_data=shal_fungi_data %>% column_to_rownames(var="plot")

#reading in and cleaning Fungi sequence file: 5-10cm
deep_fungi_data_1=read.csv("newdata/Fungi/IndianaCFIITSProp_seqtab_5_10_2022_02_24_1.csv",head =TRUE, row.names=1)
deep_fungi_data_1<-t(deep_fungi_data_1)

deep_fungi_data=as.data.frame(deep_fungi_data_1) %>% 
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "amplicon")) %>% 
  mutate(plot=as.numeric(substr(plot, 2, 5))) %>% 
  select(-upperDepth, -lowerDepth, -amplicon) %>% 
  arrange(plot)
deep_fungi_plots=deep_fungi_data$plot
deep_fungi_data=deep_fungi_data %>% column_to_rownames(var="plot")

#reading in and cleaning ECM fungi sequence file: 0-5 cm
shal_ecm_data_1=read.csv("newdata/Fungi/IndianaCFIITSProp_seqtabEcto_0_5_2022_02_24.csv",head =TRUE, row.names=1)
shal_ecm_data_1<-t(shal_ecm_data_1)

shal_ecm_data=as.data.frame(shal_ecm_data_1) %>% 
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "amplicon")) %>% 
  mutate(plot=as.numeric(substr(plot, 2, 5))) %>% 
  select(-upperDepth, -lowerDepth,-amplicon) %>% 
  arrange(plot)
shal_ecm_plots=shal_ecm_data$plot
shal_ecm_data=shal_ecm_data %>% column_to_rownames(var="plot")

#reading in and cleaning ECM fungi sequence file: 5-10cm
deep_ecm_data_1=read.csv("newdata/Fungi/IndianaCFIITSProp_seqtabEcto_5_10_2022_02_24.csv",head =TRUE, row.names=1)
deep_ecm_data_1<-t(deep_ecm_data_1)

deep_ecm_data=as.data.frame(deep_ecm_data_1) %>% 
  rownames_to_column("id") %>% 
  separate(id, into=c("plot", "upperDepth", "lowerDepth", "amplicon")) %>% 
  mutate(plot=as.numeric(substr(plot, 2, 5))) %>% 
  select(-upperDepth, -lowerDepth,-amplicon) %>% 
  arrange(plot)
deep_ecm_plots=deep_ecm_data$plot
deep_ecm_data=deep_ecm_data %>% column_to_rownames(var="plot")

#reading in county of each plot
county=read.csv("plot_county.csv") %>% 
  filter(!is.na(plotID )) %>% 
  mutate(plotID=as.character(plotID))

#compiling environmental data: AM
shal_am_clim=read.csv("newdata/AMF/Climate_0_5_02_2022.csv")
deep_am_clim=read.csv("newdata/AMF/Climate_5_10_02_2022.csv")
shal_am_soil=read.csv("newdata/AMF/fe_pH_0_5_2022_02_15.csv")
deep_am_soil=read.csv("newdata/AMF/fe_pH_5_10_2022_02_15.csv")
shal_am_geo=read.csv("newdata/AMF/Geo_0_5_02_2022.csv")
deep_am_geo=read.csv("newdata/AMF/Geo_5_10_02_2022.csv")
shal_am_productivity=read.csv("newdata/AMF/PlantProd_0_5_02_2022.csv")
deep_am_productivity=read.csv("newdata/AMF/PlantProd_5_10_02_2022.csv")
shal_am_structure=read.csv("newdata/AMF/PlantStructural_0_5_02_2022.csv")
deep_am_structure=read.csv("newdata/AMF/PlantStructural_5_10_02_2022.csv")
shal_am_treediv=read.csv("newdata/AMF/PlantTreeDiv_0_5_02_2022.csv")
deep_am_treediv=read.csv("newdata/AMF/PlantTreeDiv_5_10_02_2022.csv")


shal_am_environmental_data=shal_am_clim %>% 
  left_join(shal_am_geo, by="X") %>% 
  left_join(shal_am_soil, by=c("X"="Name")) %>% 
  left_join(shal_am_productivity, by="X") %>% 
  left_join(shal_am_structure, by="X") %>% 
  left_join(shal_am_treediv, by="X") %>% 
  drop_na() %>% 
  separate(X, into=c("plotID", "upperDepth", "lowerDepth", "amplicon")) %>% 
  select(-"upperDepth", -"lowerDepth", -"amplicon") %>% 
left_join(county, by="plotID") 

deep_am_environmental_data=deep_am_clim %>% 
  left_join(deep_am_geo, by="X") %>%
  left_join(deep_am_soil, by=c("X"="Name")) %>% 
  left_join(deep_am_productivity, by="X") %>% 
  left_join(deep_am_structure, by="X") %>% 
  left_join(deep_am_treediv, by="X") %>% 
  drop_na() %>% 
  separate(X, into=c("plotID", "upperDepth", "lowerDepth", "amplicon")) %>% 
  select(-"upperDepth", -"lowerDepth", -"amplicon")%>% 
left_join(county, by="plotID") 

#compiling environmental data: Fungi (ECM and total)
shal_fungi_clim=read.csv("newdata/Fungi/Climate_0_5_02_2022.csv")
deep_fungi_clim=read.csv("newdata/Fungi/Climate_5_10_02_2022.csv")
shal_fungi_soil=read.csv("newdata/Fungi/fe_pH_0_5_2022_02_15.csv")
deep_fungi_soil=read.csv("newdata/Fungi/fe_pH_5_10_2022_02_15.csv")
shal_fungi_geo=read.csv("newdata/Fungi/Geo_0_5_02_2022.csv")
deep_fungi_geo=read.csv("newdata/Fungi/Geo_5_10_02_2022.csv")
shal_fungi_productivity=read.csv("newdata/Fungi/PlantProd_0_5_02_2022.csv")
deep_fungi_productivity=read.csv("newdata/Fungi/PlantProd_5_10_02_2022.csv")
shal_fungi_structure=read.csv("newdata/Fungi/PlantStructural_0_5_02_2022.csv")
deep_fungi_structure=read.csv("newdata/Fungi/PlantStructural_5_10_02_2022.csv")
shal_fungi_treediv=read.csv("newdata/Fungi/PlantTreeDiv_0_5_02_2022.csv")
deep_fungi_treediv=read.csv("newdata/Fungi/PlantTreeDiv_5_10_02_2022.csv")

shal_fungi_environmental_data=shal_fungi_clim %>% 
  left_join(shal_fungi_geo, by="X") %>% 
  left_join(shal_fungi_soil, by=c("X"="Name")) %>% 
  left_join(shal_fungi_productivity, by="X") %>% 
  left_join(shal_fungi_structure, by="X") %>% 
  left_join(shal_fungi_treediv, by="X") %>% 
  drop_na() %>% 
  separate(X, into=c("plotID", "upperDepth", "lowerDepth", "amplicon")) %>% 
  select(-"upperDepth", -"lowerDepth", -"amplicon")%>% 
left_join(county, by="plotID") 

deep_fungi_environmental_data=deep_fungi_clim %>% 
  left_join(deep_fungi_geo, by="X") %>%
  left_join(deep_fungi_soil, by=c("X"="Name")) %>% 
  left_join(deep_fungi_productivity, by="X") %>% 
  left_join(deep_fungi_structure, by="X") %>% 
  left_join(deep_fungi_treediv, by="X") %>% 
  drop_na() %>% 
  separate(X, into=c("plotID", "upperDepth", "lowerDepth", "amplicon")) %>% 
  select(-"upperDepth", -"lowerDepth", -"amplicon")%>% 
left_join(county, by="plotID") 


#compiling environmental data: Bacteria
shal_bacteria_clim=read.csv("newdata/Bacteria/Climate_0_5_02_2022.csv")
deep_bacteria_clim=read.csv("newdata/Bacteria/Climate_5_10_02_2022.csv")
shal_bacteria_soil=read.csv("newdata/Bacteria/fe_pH_0_5_2022_02_15.csv")
deep_bacteria_soil=read.csv("newdata/Bacteria/fe_pH_5_10_2022_02_15.csv")
shal_bacteria_geo=read.csv("newdata/Bacteria/Geo_0_5_02_2022.csv")
deep_bacteria_geo=read.csv("newdata/Bacteria/Geo_5_10_02_2022.csv")
shal_bacteria_productivity=read.csv("newdata/Bacteria/PlantProd_0_5_02_2022.csv")
deep_bacteria_productivity=read.csv("newdata/Bacteria/PlantProd_5_10_02_2022.csv")
shal_bacteria_structure=read.csv("newdata/Bacteria/PlantStructural_0_5_02_2022.csv")
deep_bacteria_structure=read.csv("newdata/Bacteria/PlantStructural_5_10_02_2022.csv")
shal_bacteria_treediv=read.csv("newdata/Bacteria/PlantTreeDiv_0_5_02_2022.csv")
deep_bacteria_treediv=read.csv("newdata/Bacteria/PlantTreeDiv__5_10_02_2022.csv")

shal_bacteria_environmental_data=shal_bacteria_clim %>% 
  left_join(shal_bacteria_geo, by="X") %>% 
  left_join(shal_bacteria_soil, by=c("X"="Name")) %>% 
  left_join(shal_bacteria_productivity, by="X") %>% 
  left_join(shal_bacteria_structure, by="X") %>% 
  left_join(shal_bacteria_treediv, by="X") %>% 
  drop_na() %>% 
  separate(X, into=c("plotID", "upperDepth", "lowerDepth", "amplicon")) %>% 
  select(-"upperDepth", -"lowerDepth", -"amplicon")%>% 
left_join(county, by="plotID") 

deep_bacteria_environmental_data=deep_bacteria_clim %>% 
  left_join(deep_bacteria_geo, by="X") %>%
  left_join(deep_bacteria_soil, by=c("X"="Name")) %>% 
  left_join(deep_bacteria_productivity, by="X") %>% 
  left_join(deep_bacteria_structure, by="X") %>% 
  left_join(deep_bacteria_treediv, by="X") %>% 
  drop_na() %>% 
  separate(X, into=c("plotID", "upperDepth", "lowerDepth", "amplicon")) %>% 
  select(-"upperDepth", -"lowerDepth", -"amplicon")%>% 
left_join(county, by="plotID") 




```


```{r AM_ad, warning=F, echo=F}
shal_AM_shannon <- diversity(shal_amfungi_data, index="shannon") 
shal_AM_shannon=as.data.frame(shal_AM_shannon) %>% 
  rownames_to_column("plotID") 

shal_AM_simpson <- diversity(shal_amfungi_data, index="simpson")
shal_AM_simpson=as.data.frame(shal_AM_simpson) %>% 
  rownames_to_column("plotID") 

shal_AM_invsimpson <- diversity(shal_amfungi_data, index="invsimpson")
shal_AM_invsimpson=as.data.frame(shal_AM_invsimpson) %>% 
  rownames_to_column("plotID") 

shal_AM_species_richness = shal_amfungi_data %>% 
  rownames_to_column("plotID") %>% 
mutate(shal_AM_species_richness= rowSums(shal_amfungi_data != 0)) %>% 
  select(plotID, shal_AM_species_richness)

deep_AM_shannon <- diversity(deep_amfungi_data, index="shannon") 
deep_AM_shannon=as.data.frame(deep_AM_shannon) %>% 
  rownames_to_column("plotID") 

deep_AM_simpson <- diversity(deep_amfungi_data, index="simpson")
deep_AM_simpson=as.data.frame(deep_AM_simpson) %>% 
  rownames_to_column("plotID") 

deep_AM_invsimpson <- diversity(deep_amfungi_data, index="invsimpson")
deep_AM_invsimpson=as.data.frame(deep_AM_invsimpson) %>% 
  rownames_to_column("plotID") 

deep_AM_species_richness = deep_amfungi_data %>% 
  rownames_to_column("plotID") %>% 
mutate(deep_AM_species_richness= rowSums(deep_amfungi_data != 0)) %>% 
  select(plotID, deep_AM_species_richness)

```

```{r Fungi_ad, warning=F, echo=F}
shal_Fungi_shannon <- diversity(shal_fungi_data, index="shannon") 
shal_Fungi_shannon=as.data.frame(shal_Fungi_shannon) %>% 
  rownames_to_column("plotID") 

shal_Fungi_simpson <- diversity(shal_fungi_data, index="simpson")
shal_Fungi_simpson=as.data.frame(shal_Fungi_simpson) %>% 
  rownames_to_column("plotID") 

shal_Fungi_invsimpson <- diversity(shal_fungi_data, index="invsimpson")
shal_Fungi_invsimpson=as.data.frame(shal_Fungi_invsimpson) %>% 
  rownames_to_column("plotID") 

shal_Fungi_species_richness = shal_fungi_data %>% 
  rownames_to_column("plotID") %>% 
mutate(shal_Fungi_species_richness= rowSums(shal_fungi_data != 0)) %>% 
  select(plotID, shal_Fungi_species_richness)

deep_Fungi_shannon <- diversity(deep_fungi_data, index="shannon") 
deep_Fungi_shannon=as.data.frame(deep_Fungi_shannon) %>% 
  rownames_to_column("plotID") 

deep_Fungi_simpson <- diversity(deep_fungi_data, index="simpson")
deep_Fungi_simpson=as.data.frame(deep_Fungi_simpson) %>% 
  rownames_to_column("plotID") 

deep_Fungi_invsimpson <- diversity(deep_fungi_data, index="invsimpson")
deep_Fungi_invsimpson=as.data.frame(deep_Fungi_invsimpson) %>% 
  rownames_to_column("plotID") 

deep_Fungi_species_richness = deep_fungi_data %>% 
  rownames_to_column("plotID") %>% 
mutate(deep_Fungi_species_richness= rowSums(deep_fungi_data != 0)) %>% 
  select(plotID, deep_Fungi_species_richness)

```

```{r ECM_ad, warning=F, echo=F}
shal_ECM_shannon <- diversity(shal_ecm_data, index="shannon") 
shal_ECM_shannon=as.data.frame(shal_ECM_shannon) %>% 
  rownames_to_column("plotID") 

shal_ECM_simpson <- diversity(shal_ecm_data, index="simpson")
shal_ECM_simpson=as.data.frame(shal_ECM_simpson) %>% 
  rownames_to_column("plotID") 

shal_ECM_invsimpson <- diversity(shal_ecm_data, index="invsimpson")
shal_ECM_invsimpson=as.data.frame(shal_ECM_invsimpson) %>% 
  rownames_to_column("plotID") 
shal_ECM_invsimpson=shal_ECM_invsimpson %>%  dplyr::filter(plotID != "1239")

shal_ECM_species_richness = shal_ecm_data %>% 
  rownames_to_column("plotID") %>% 
mutate(shal_ECM_species_richness= rowSums(shal_ecm_data != 0)) %>% 
  select(plotID, shal_ECM_species_richness)


deep_ECM_shannon <- diversity(deep_ecm_data, index="shannon") 
deep_ECM_shannon=as.data.frame(deep_ECM_shannon) %>% 
  rownames_to_column("plotID") 

deep_ECM_simpson <- diversity(deep_ecm_data, index="simpson")
deep_ECM_simpson=as.data.frame(deep_ECM_simpson) %>% 
  rownames_to_column("plotID") 

deep_ECM_invsimpson <- diversity(deep_ecm_data, index="invsimpson")
deep_ECM_invsimpson=as.data.frame(deep_ECM_invsimpson) %>% 
  rownames_to_column("plotID") 

deep_ECM_species_richness = deep_ecm_data %>% 
  rownames_to_column("plotID") %>% 
mutate(deep_ECM_species_richness= rowSums(deep_ecm_data != 0)) %>% 
  select(plotID, deep_ECM_species_richness)

```

```{r Bact_ad, warning=F, echo=F}
shal_Bact_shannon <- diversity(shal_bacteria_data, index="shannon") 
shal_Bact_shannon=as.data.frame(shal_Bact_shannon) %>% 
  rownames_to_column("plotID") 

shal_Bact_simpson <- diversity(shal_bacteria_data, index="simpson")
shal_Bact_simpson=as.data.frame(shal_Bact_simpson) %>% 
  rownames_to_column("plotID") 

shal_Bact_invsimpson <- diversity(shal_bacteria_data, index="invsimpson")
shal_Bact_invsimpson=as.data.frame(shal_Bact_invsimpson) %>% 
  rownames_to_column("plotID") 

shal_Bact_species_richness = shal_bacteria_data %>% 
  rownames_to_column("plotID") %>% 
mutate(shal_Bact_species_richness= rowSums(shal_bacteria_data != 0)) %>% 
  select(plotID, shal_Bact_species_richness)


deep_Bact_shannon <- diversity(deep_bacteria_data, index="shannon") 
deep_Bact_shannon=as.data.frame(deep_Bact_shannon) %>% 
  rownames_to_column("plotID") 

deep_Bact_simpson <- diversity(deep_bacteria_data, index="simpson")
deep_Bact_simpson=as.data.frame(deep_Bact_simpson) %>% 
  rownames_to_column("plotID") 

deep_Bact_invsimpson <- diversity(deep_bacteria_data, index="invsimpson")
deep_Bact_invsimpson=as.data.frame(deep_Bact_invsimpson) %>% 
  rownames_to_column("plotID") 

deep_Bact_species_richness = deep_bacteria_data %>% 
  rownames_to_column("plotID") %>% 
mutate(deep_Bact_species_richness= rowSums(deep_bacteria_data != 0)) %>% 
  select(plotID, deep_Bact_species_richness)


```

```{r diversity_metrics, echo=F, message=F, warning=F}

shal_AM_diversity_data=shal_am_environmental_data %>% 
  left_join(shal_AM_shannon, by="plotID") %>%
  left_join(shal_AM_simpson, by="plotID") %>%
  left_join(shal_AM_invsimpson, by="plotID") %>%
  left_join(shal_AM_species_richness, by="plotID") %>% 
  mutate(shal_AM_species_evenness=shal_AM_shannon/log(shal_AM_species_richness))

shal_Fungi_diversity_data=shal_fungi_environmental_data %>% 
  left_join(shal_Fungi_shannon, by="plotID") %>% 
  left_join(shal_Fungi_simpson, by="plotID") %>%
  left_join(shal_Fungi_invsimpson, by="plotID") %>%
   left_join(shal_Fungi_species_richness, by="plotID") %>% 
  mutate(shal_Fungi_species_evenness=shal_Fungi_shannon/log(shal_Fungi_species_richness)) 

shal_ECM_diversity_data=shal_fungi_environmental_data %>% 
  left_join(shal_ECM_shannon, by="plotID") %>% 
  left_join(shal_ECM_simpson, by="plotID") %>%
  left_join(shal_ECM_invsimpson, by="plotID") %>%
   left_join(shal_ECM_species_richness, by="plotID") %>% 
  mutate(shal_ECM_species_evenness=shal_ECM_shannon/log(shal_ECM_species_richness)) 

shal_Bacteria_diversity_data=shal_bacteria_environmental_data%>% 
  left_join(shal_Bact_shannon, by="plotID") %>%
  left_join(shal_Bact_simpson, by="plotID") %>%
  left_join(shal_Bact_invsimpson, by="plotID") %>%  
  left_join(shal_Bact_species_richness, by="plotID") %>% 
  mutate(shal_Bact_species_evenness=shal_Bact_shannon/log(shal_Bact_species_richness)) 

deep_AM_diversity_data=deep_am_environmental_data %>% 
  left_join(deep_AM_shannon, by="plotID") %>%
  left_join(deep_AM_simpson, by="plotID") %>%
  left_join(deep_AM_invsimpson, by="plotID") %>%
  left_join(deep_AM_species_richness, by="plotID") %>% 
  mutate(deep_AM_species_evenness=deep_AM_shannon/log(deep_AM_species_richness))

deep_Fungi_diversity_data=deep_fungi_environmental_data %>% 
  left_join(deep_Fungi_shannon, by="plotID") %>% 
  left_join(deep_Fungi_simpson, by="plotID") %>%
  left_join(deep_Fungi_invsimpson, by="plotID") %>%
   left_join(deep_Fungi_species_richness, by="plotID") %>% 
  mutate(deep_Fungi_species_evenness=deep_Fungi_shannon/log(deep_Fungi_species_richness)) 

deep_ECM_diversity_data=deep_fungi_environmental_data %>% 
  left_join(deep_ECM_shannon, by="plotID") %>% 
  left_join(deep_ECM_simpson, by="plotID") %>%
  left_join(deep_ECM_invsimpson, by="plotID") %>%
   left_join(deep_ECM_species_richness, by="plotID") %>% 
  mutate(deep_ECM_species_evenness=deep_ECM_shannon/log(deep_ECM_species_richness)) 

deep_Bacteria_diversity_data=deep_bacteria_environmental_data%>% 
  left_join(deep_Bact_shannon, by="plotID") %>%
  left_join(deep_Bact_simpson, by="plotID") %>%
  left_join(deep_Bact_invsimpson, by="plotID") %>%  
  left_join(deep_Bact_species_richness, by="plotID") %>% 
  mutate(deep_Bact_species_evenness=deep_Bact_shannon/log(deep_Bact_species_richness)) 

```


```{r full_models }

#Currently in random effect of county mode: convert to regular linear models with lm function and syntax change
 
library(nlme)
library(MuMIn)
#shallow AM:
shallow_am_2= lme(shal_AM_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years, random=(~1| county), data=shal_AM_diversity_data, na.action=na.omit)
summary(shallow_am_2)
r.squaredGLMM(shallow_am_2)


#deep AM:
deep_am_2= lme(deep_AM_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years,random=(~1| county), data=deep_AM_diversity_data, na.action=na.omit)
summary(deep_am_2)
r.squaredGLMM(shallow_am_2)


#shallow EM:
shallow_em_2= lme(shal_ECM_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years,random=(~1| county), data=shal_ECM_diversity_data, na.action=na.omit)
summary(shallow_em_2)
r.squaredGLMM(shallow_am_2)


#deep EM:
deep_em_2= lme(deep_ECM_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years,random=(~1| county), data=deep_ECM_diversity_data, na.action=na.omit)
summary(deep_em_2)
r.squaredGLMM(shallow_am_2)



#shallow bacteria:
shallow_bacteria_2= lme(shal_Bact_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years,random=(~1| county), data=shal_Bacteria_diversity_data, na.action=na.omit)
summary(shallow_bacteria_2)
r.squaredGLMM(shallow_am_2)


#deep bacteria:
deep_bacteria_2= lme(deep_Bact_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years,random=(~1| county), data=deep_Bacteria_diversity_data, na.action=na.omit)
summary(deep_bacteria_2)
r.squaredGLMM(shallow_am_2)


#shallow fungi:
shallow_fungi_2= lme(shal_Fungi_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years,random=(~1| county), data=shal_Fungi_diversity_data, na.action=na.omit)
summary(shallow_fungi_2)
r.squaredGLMM(shallow_am_2)


#deep fungi:
deep_fungi_2= lme(deep_Fungi_invsimpson~cn+pH+Fe_percent+BAI+vert.sd+VAI+VCI+tree_richness+AMdominance+stand_age_years, random=(~1|county), data=deep_Fungi_diversity_data, na.action=na.omit)
summary(deep_fungi_2)
r.squaredGLMM(deep_fungi_2)

#partial_r2(deep_fungi_2) #(for lm)

tab_model(shallow_am_2, deep_am_2, shallow_em_2, deep_em_2, shallow_bacteria_2, deep_bacteria_2, shallow_fungi_2, deep_fungi_2, show.se = TRUE, show.ci = FALSE, show.std = "std2", digits = 2, digits.re = 2)

```

## pH influences alpha diversity of AM fungi, bacteria, and total fungi:

```{r pH_fig, echo=F, message=F, warning=F}


#calculating the marginal effect of pH on microbial group alpha diversity 

shal_AM_E1 = ggeffect(shallow_am_2, terms = c("pH"), type = "random")
shal_Fun_E1= ggeffect(shallow_fungi_2, terms = c("pH"), type = "random")
shal_Bact_E1= ggeffect(shallow_bacteria_2, terms = c("pH"), type = "random")
shal_ECM_E1= ggeffect(shallow_em_2, terms=c("pH"), type="random")

deep_AM_E1 = ggeffect(deep_am_2, terms = c("pH"), type = "random")
deep_Fun_E1= ggeffect(deep_fungi_2, terms = c("pH"), type = "random")
deep_Bact_E1= ggeffect(deep_bacteria_2, terms = c("pH"), type = "random")
deep_ECM_E1= ggeffect(deep_em_2, terms=c("pH"), type="random")

colors=c("0-5 cm"= '#D2BF07', "5-10 cm" = "#648FFF")


a <- ggplot() +
  geom_point(data = shal_AM_diversity_data, aes(x = pH, y = shal_AM_invsimpson, color="0-5 cm"), size=3) +
  geom_line(data = shal_AM_E1, aes(x = x, y = predicted,color="0-5 cm"), size = 1.5) +
  geom_point(data = deep_AM_diversity_data, aes(x = pH, y = deep_AM_invsimpson,color="5-10 cm"), size=3) +
  geom_line(data = deep_AM_E1, aes(x = x, y = predicted,color="5-10 cm"), size = 1.5) +
  labs(x= "Soil pH", y="Alpha diversity of AM fungi", color="Soil Depth" )+
  scale_color_manual(values=colors)+
  theme_cowplot()


b <- ggplot() +
  geom_point(data = shal_Fungi_diversity_data, aes(x = pH, y = shal_Fungi_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_Fungi_diversity_data, aes(x = pH, y = deep_Fungi_invsimpson,color="5-10 cm"), size=3) +
  geom_line(data = deep_Fun_E1, aes(x = x, y = predicted,color="5-10 cm"), size = 1.5) +
  labs(x= "Soil pH", y="Alpha diversity of total fungi" ,color="Soil Depth")+
  scale_color_manual(values=colors)+
  theme_cowplot()


  c<- ggplot()+
  geom_point(data = shal_Bacteria_diversity_data, aes(x = pH, y = shal_Bact_invsimpson, color="0-5 cm"), size=3) +
  geom_line(data = shal_Bact_E1, aes(x = x, y = predicted, color="0-5 cm"), size = 1.5) +
  geom_point(data = deep_Bacteria_diversity_data, aes(x = pH, y = deep_Bact_invsimpson,color="5-10 cm"), size=3) +
  geom_line(data = deep_Bact_E1, aes(x = x, y = predicted,color="5-10 cm"), size = 1.5) +
labs(x= "Soil pH", y="Alpha diversity of bacteria"  ,color="Soil Depth")+
  scale_color_manual(values=colors)+
  theme_cowplot()

   d <- ggplot()+
  geom_point(data = shal_ECM_diversity_data, aes(x = pH, y = shal_ECM_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_ECM_diversity_data, aes(x = pH, y = deep_ECM_invsimpson, color="5-10 cm"), size=3) +
labs(x= "Soil pH", y="Alpha diversity of EM fungi" ,color="Soil Depth")+
  scale_color_manual(values=colors)+
  theme_cowplot()

ggarrange(c,b,a,d, labels=c("a", "b", "c", "d" ), nrow=2, ncol=2, legend="right", common.legend=TRUE)


ggsave("Figure_S2.pdf", width = 10.5 , height = 8, units = c("in"))
  

```

```{r stand_age_fig, echo=F, message=F, warning=F}
 shal_Bact_E2 = ggeffect(shallow_bacteria_2, terms = c("stand_age_years"), type = "random")
 shal_Fun_E2= ggeffect(shallow_fungi_2, terms = c("stand_age_years"), type = "random") #not significant
 shal_AM_E2= ggeffect(shallow_am_2, terms = c("stand_age_years"), type = "random")
 shal_EM_E2= ggeffect(shallow_em_2, terms=c("stand_age_years"), type="random")
 
 deep_Bact_E2 = ggeffect(deep_bacteria_2, terms = c("stand_age_years"), type = "random")
 deep_Fun_E2= ggeffect(deep_fungi_2, terms = c("stand_age_years"), type = "random")
 deep_AM_E2= ggeffect(deep_am_2, terms = c("stand_age_years"), type = "random")
 deep_EM_E2= ggeffect(deep_em_2,  terms=c("stand_age_years"), type="random")#not significant


 a <- ggplot() +
  geom_point(data = shal_Bacteria_diversity_data, aes(x = stand_age_years, y = shal_Bact_invsimpson, color="0-5 cm"), size=3) +
  geom_line(data = shal_Bact_E2, aes(x = x, y = predicted, color="0-5 cm"), size = 1.5) +
  geom_point(data = deep_Bacteria_diversity_data, aes(x = stand_age_years, y = deep_Bact_invsimpson, color="5-10 cm"), size=3) +
  geom_line(data = deep_Bact_E2, aes(x = x, y = predicted, color="5-10 cm"), size = 1.5) +
  labs(x= "Stand age (years)", y="Alpha diversity of bacteria", color="Soil Depth" )+
   scale_color_manual(values=colors)+
  theme_cowplot()+
  geom_text(aes(x=45, y=700, label="0-5 cm: r = -0.41; p = 0.03\n5-10 cm: r = -0.47; p = 0.009"))


b <- ggplot() +
  geom_point(data = shal_Fungi_diversity_data, aes(x = stand_age_years, y = shal_Fungi_invsimpson, color="0-5 cm"), size=3) +
   geom_point(data = deep_Fungi_diversity_data, aes(x = stand_age_years, y = deep_Fungi_invsimpson, color="5-10 cm"), size=3) +
  geom_line(data = deep_Fun_E2, aes(x = x, y = predicted,color="5-10 cm"), size = 1.5) +
  labs(x= "Stand age (years)", y="Alpha diversity of total fungi", color="Soil Depth" )+
   scale_color_manual(values=colors)+
  theme_cowplot()+
  geom_text(aes(x=45, y=110, label="5-10 cm: r = -0.72; p < 0.001"))


  c <- ggplot()+
  geom_point(data = shal_AM_diversity_data, aes(x = stand_age_years, y = shal_AM_invsimpson, color="0-5 cm"), size=3) +
  geom_line(data = shal_AM_E2, aes(x = x, y = predicted, color="0-5 cm"), size = 1.5,  linetype="dashed") +
     geom_point(data = deep_AM_diversity_data, aes(x = stand_age_years, y = deep_AM_invsimpson,color="5-10 cm"), size=3) +
  geom_line(data = deep_AM_E2, aes(x = x, y = predicted,color="5-10 cm"), size = 1.5) +
labs(x= "Stand age (years)", y="Alpha diversity of AM fungi", color="Soil Depth" )+
   scale_color_manual(values=colors)+
  theme_cowplot()+
    ylim(0, 34)+
  geom_text(aes(x=45, y=32, label="0-5 cm: r = -0.53; p = 0.005\n5-10 cm: r = -0.36; p = 0.088"))


   d <- ggplot()+
  geom_point(data = shal_ECM_diversity_data, aes(x = stand_age_years, y = shal_ECM_invsimpson, color="0-5 cm"), size=3) +
      geom_point(data = deep_ECM_diversity_data, aes(x = stand_age_years, y = deep_ECM_invsimpson, color="5-10 cm"), size=3) +
       geom_line(data = shal_EM_E2, aes(x = x, y = predicted, color="0-5 cm"), size = 1.5) +
labs(x= "Stand age (years)", y="Alpha diversity of EM fungi", color="Soil Depth" )+
   scale_color_manual(values=colors)+
  theme_cowplot()+
  geom_text(aes(x=45, y=15, label="0-5 cm: r = 0.34; p = 0.046"))
 
   
   ggarrange(a,b,c,d, labels=c("a", "b", "c", "d"), nrow=2, ncol=2, legend="right", common.legend=TRUE)
   
     ggsave("Figure_3.pdf", width = 10 , height = 8, units = c("in"))

     
```

```{r am_dom fig}
shal_Bact_E3= ggeffect(shal_bacteria_invsim_plantrichness, terms = c("AMdominance"), type = "random")
 shal_Fun_E3= ggeffect(shal_fungi_invsim_plantrichness, terms=c("AMdominance"), type="random")
 deep_Bact_E3= ggeffect(deep_bacteria_invsim_plantrichness, terms = c("AMdominance"), type = "random")
 deep_Fun_E3= ggeffect(deep_fungi_invsim_plantrichness, terms=c("AMdominance"), type="random")
 
 a <- ggplot()+
  geom_point(data = shal_Bacteria_diversity_data, aes(x = AMdominance, y = shal_Bact_invsimpson, color="0-5 cm"), size=3) +
  geom_line(data = shal_Bact_E3, aes(x = x, y = predicted, color="0-5 cm"), size = 1.5,  linetype="dashed") +
     geom_point(data = deep_Bacteria_diversity_data, aes(x = AMdominance, y = deep_Bact_invsimpson,color="5-10 cm"), size=3) +
  geom_line(data = deep_Bact_E3, aes(x = x, y = predicted,color="5-10 cm"), size = 1.5) +
labs(x= "Proportion of tree basal area\nfrom AM-associated species", y="Alpha diversity of Bacteria", color="Soil Depth" )+
   scale_color_manual(values=colors)+
  theme_cowplot()+
  geom_text(aes(x=0.25, y=590, label="0-5 cm: r = 0.52; p = 0.054\n5-10 cm: r = 0.46; p = 0.02"))


  b <- ggplot()+
  geom_point(data = shal_Fungi_diversity_data, aes(x = AMdominance, y = shal_Fungi_invsimpson, color="0-5 cm"), size=3) +
      geom_point(data = deep_Fungi_diversity_data, aes(x = AMdominance, y = deep_Fungi_invsimpson, color="5-10 cm"), size=3) +
  geom_line(data = deep_Fun_E3, aes(x = x, y = predicted, color="5-10 cm"), size = 1.5) +
labs(x= "Proportion of tree basal area\nfrom AM-associated species", y="Alpha diversity of Total fungi", color="Soil Depth" )+
   scale_color_manual(values=colors)+
  theme_cowplot()+
  geom_text(aes(x=0.25, y=110, label="5-10 cm: r = 0.65; p = 0.01"))
 
   
```

```{r EM_VAI fig}
shal_ECM_E4= ggeffect(shallow_em_2, terms = c("VAI"), type = "random")
 
a <- ggplot()+
  geom_point(data = shal_ECM_diversity_data, aes(x = VAI, y = shal_ECM_invsimpson, color="0-5 cm"), size=3) +
  geom_line(data = shal_ECM_E4, aes(x = x, y = predicted, color="0-5 cm"), size = 1.5) +
  geom_point(data = deep_ECM_diversity_data, aes(x = VAI, y = deep_ECM_invsimpson, color="5-10 cm"), size=3) +
  labs(x= "Vegetation Area Index", y="Alpha diversity of EM fungi", color="Soil Depth" )+
  scale_color_manual(values=colors)+
  theme_cowplot()

b <- ggplot()+
  geom_point(data = shal_AM_diversity_data, aes(x = VAI, y = shal_AM_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_AM_diversity_data, aes(x = VAI, y = deep_AM_invsimpson, color="5-10 cm"), size=3) +
  labs(x= "Vegetation Area Index", y="Alpha diversity of AM fungi", color="Soil Depth" )+
  scale_color_manual(values=colors)+
  theme_cowplot()

c <- ggplot()+
  geom_point(data = shal_Bacteria_diversity_data, aes(x = VAI, y = shal_Bact_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_Bacteria_diversity_data, aes(x = VAI, y = deep_Bact_invsimpson, color="5-10 cm"), size=3) +
  labs(x= "Vegetation Area Index", y="Alpha diversity of Bacteria", color="Soil Depth" )+
  scale_color_manual(values=colors)+
  theme_cowplot()
 
d <- ggplot()+
  geom_point(data = shal_Fungi_diversity_data, aes(x = VAI, y = shal_Fungi_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_Fungi_diversity_data, aes(x = VAI, y = deep_Fungi_invsimpson, color="5-10 cm"), size=3) +
  labs(x= "Vegetation Area Index", y="Alpha diversity of Fungi", color="Soil Depth" )+
  scale_color_manual(values=colors)+
  theme_cowplot() 
 
  ggarrange(a,b,c,d, labels=c("a", "b", "c", "d"), nrow=2, ncol=2, legend="right", common.legend=TRUE)
      ggsave("VAI_fig.pdf", width = 10 , height = 8, units = c("in")) 
      
```

```{r myc_richnesses}


cor.test(shal_AM_diversity_data$AMtreerichness,shal_AM_diversity_data$shal_AM_invsimpson, method="pearson") 
#r=0.24
#  p=0.16

cor.test(deep_AM_diversity_data$AMtreerichness,deep_AM_diversity_data$deep_AM_invsimpson, method="pearson") 
#r=0.28
#  p=0.11

cor.test(shal_ECM_diversity_data$EMtreerichness,shal_ECM_diversity_data$shal_ECM_invsimpson, method="pearson")
#r=-0.097
#  p=0.57

cor.test(deep_ECM_diversity_data$EMtreerichness,deep_ECM_diversity_data$deep_ECM_invsimpson, method="pearson") 
#r=0.19
#  p=0.26

a <- ggplot()+
  geom_point(data = shal_AM_diversity_data, aes(x = AMtreerichness, y = shal_AM_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_AM_diversity_data, aes(x = AMtreerichness, y = deep_AM_invsimpson, color="5-10 cm"), size=3) +
  labs(x= "AM tree species richness", y="Alpha diversity of AM Fungi", color="Soil Depth" )+
  scale_color_manual(values=colors)+
  geom_text(aes(x=0.85, y=26.5, label="0-5: r = 0.24; p = 0.16\n5-10: r= 0.28; p= 0.11"))+
  theme_cowplot()
 
b <- ggplot()+
  geom_point(data = shal_ECM_diversity_data, aes(x = EMtreerichness, y = shal_ECM_invsimpson, color="0-5 cm"), size=3) +
  geom_point(data = deep_ECM_diversity_data, aes(x = EMtreerichness, y = deep_ECM_invsimpson, color="5-10 cm"), size=3) +
  labs(x= "EM tree species richness", y="Alpha diversity of EM Fungi", color="Soil Depth" )+
  scale_color_manual(values=colors)+
   geom_text(aes(x=0.5, y=20, label="0-5: r = -0.097; p = 0.57\n5-10: r= 0.19; p= 0.26"))+
  theme_cowplot() 
 
  ggarrange(a,b, labels=c("a", "b"), nrow=1, ncol=2, legend="right", common.legend=TRUE)
      ggsave("AM_EM_richness.pdf", width = 12 , height = 5, units = c("in")) 


```


```{r am_stand_age}
 x <- ggplot()+
  geom_point(data = deep_am_environmental_data, aes(x = stand_age_years, y = AMdominance))+
  geom_smooth(method="lm")+
labs(x= "stand age (years)", y="Proportion of tree basal area\nfrom AM-associated species" )+
  theme_cowplot()


#-0.66: older stands have less AM trees
cor.test(deep_am_environmental_data$AMdominance,deep_am_environmental_data$stand_age_years, method="pearson")

#older stands do not have less AM tree richness
cor.test(deep_am_environmental_data$AMtreerichness,deep_am_environmental_data$stand_age_years, method="pearson")

#older stands have richer EM tree communities (r=0.49)
cor.test(deep_fungi_environmental_data$EMtreerichness,deep_fungi_environmental_data$stand_age_years, method="pearson")

#In shallow soil, AM fungal richness not correlated with AM tree richness:
cor.test(shal_AM_diversity_data$AMtreerichness,shal_AM_diversity_data$shal_AM_invsimpson, method="pearson")

#Nor in deep soil:
cor.test(deep_AM_diversity_data$AMtreerichness,deep_AM_diversity_data$deep_AM_invsimpson, method="pearson")


#But AM dominance is?
#yes in shallow soil
cor.test(shal_AM_diversity_data$AMdominance,shal_AM_diversity_data$shal_AM_invsimpson, method="pearson")
#not for deep
cor.test(deep_AM_diversity_data$AMdominance,deep_AM_diversity_data$deep_AM_invsimpson, method="pearson")

#So shallow soil: more AM basal area makes AM fungal community richer, not necessarily because of an increase in AM tree species richness though. 

#ECM fungal richness and EM tree richness correlated?:
#shallow:
cor.test(shal_ECM_diversity_data$EMtreerichness,shal_ECM_diversity_data$shal_ECM_invsimpson, method="pearson")
#not at all

#Deep soil?
cor.test(deep_ECM_diversity_data$EMtreerichness,deep_ECM_diversity_data$deep_ECM_invsimpson, method="pearson")
#nope

#And ECM tree dominance is not correlated with ECM fungal richness
#not for shallow
cor.test(shal_ECM_diversity_data$AMdominance,shal_ECM_diversity_data$shal_ECM_invsimpson, method="pearson")

#not for deep
cor.test(deep_ECM_diversity_data$AMdominance,deep_ECM_diversity_data$deep_ECM_invsimpson, method="pearson")


```


```{r correlations, echo=F, message=F, warning=F}

library(dichromat)
cor_df=deep_fungi_environmental_data %>% 
  dplyr::select(-plotID, -TAP, -MAT, -GPS_LAT, -GPS_LON, -BAtotal_2020) %>% 
  drop_na()
M=cor(cor_df)  
colnames(M)= c("Soil % N", "Soil % C", "Soil C:N", "Soil pH", "Soil % Fe", "Stand age", "Basal area increment", "Vert SD", "VAI", "VCI", "Tree richness", "AM dominance", "AM tree richness", "EM tree richness")
rownames(M)=c("Soil % N", "Soil % C", "Soil C:N", "Soil pH", "Soil % Fe", "Stand age", "Basal area increment", "Vert SD", "VAI", "VCI", "Tree richness", "AM dominance", "AM tree richness", "EM tree richness")
my_pal=colorRampPalette(c("blue","white","red"))

pdf(file = "CFI_alpha_correlations.pdf", width=8, height=8)
corrplot::corrplot(M, method="color", type="upper", diag=F, addCoef.col = "black", col = my_pal(n=200), number.cex=0.70)
dev.off()

```


```{r county_effect}

am_alpha_county=ggplot()+
  geom_boxplot(data = shal_AM_diversity_data, aes(x = county, y = shal_AM_invsimpson, fill="0-5 cm"), size=1) +
  geom_boxplot(data = deep_AM_diversity_data, aes(x = county, y = deep_AM_invsimpson, fill="5-10 cm"), size=1) +
  labs(x= "County", y="Alpha diversity of AM Fungi", fill="Soil Depth" )+
  scale_fill_manual(values=colors)+
  theme_cowplot()

am_alpha_county

```

